# Generated by Django 3.1.1 on 2020-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fflight', models.CharField(max_length=122)),
                ('ffrom', models.CharField(max_length=122)),
                ('fto', models.CharField(max_length=122)),
                ('date1', models.CharField(max_length=122)),
                ('date2', models.CharField(max_length=122)),
                ('adult', models.CharField(max_length=122)),
                ('child', models.CharField(max_length=122)),
                ('fclass', models.CharField(max_length=122)),
            ],
        ),
    ]
