# Generated by Django 3.1.1 on 2020-09-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date2',
            field=models.DateField(),
        ),
    ]
