# Generated by Django 3.1.1 on 2020-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200921_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='sflight',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
    ]
