# Generated by Django 3.1.1 on 2020-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_flight_sflight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='sflight',
            field=models.TextField(),
        ),
    ]
