# Generated by Django 3.2.9 on 2022-07-26 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0007_airlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('airlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.airlines')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
